export { default as BoliviaCards } from './Cards/BoliviaCards'
export { default as BoliviaCardsData } from './CardsData/BoliviaCardsData'
export { default as BoliviaMap } from './Map/BoliviaMap'
//export { default as BoliviaChart } from './Charts/BoliviaChart'
export { default as DepartmentsChart } from './Charts/DepartmentsChart'
export { default as DepartmentsTable } from './Table/DepartmentsTable'