//export { default as BoliviaCardsData } from './CardsData/BoliviaCardsData'
export { default as SudamericaMap } from './Map/SudamericaMap'
export { default as SudamericaCard } from './Cards/SudCardData'
export { default as SudamericaChart } from './Charts/SudChart'
export { default as SudamericaTable } from './Table/SudamericaTable'